In [2]:
import pandas as pd
expense_data = []
print("Expense Tracker Initialized")

Expense Tracker Initialized

In [5]:
def add_expense(name, amount, category):
    expense = {
        "Expense Name": name,
        "Amount": amount,
        "Category": category,
    }
    expense_data.append(expense)
    print(f"\n Expense '{name}' added successfully!")

def display_expenses():
    if not expense_data:
        print("\n No expenses recorded yet.")
        return None

    df = pd.DataFrame(expense_data)
    return df

def get_total_expenses():
    if not expense_data:
        return 0

    total = sum(exp["Amount"] for exp in expense_data)
    return total

def filter_expenses(category_name):
    if not expense_data:
        print("\n No expenses recorded yet.")
        return None

    df = pd.DataFrame(expense_data)

    filtered_df = df[df["Category"].str.lower() == category_name.lower()]

    if filtered_df.empty:
        print(f"\n No expenses found in '{category_name}' category.")
        return None

    return filtered_df

In [6]:
while True:
    print("\n--- Personal Expense Tracker ---")
    print("1. Add Expense")
    print("2. View All Expenses")
    print("3. View Total Expenses")
    print("4. Filter Expenses by Category")
    print("5. Exit")
    
    choice = input("\nUser choice (1-5): ")
    
    if choice == '1':
        name = input("Enter expense name (e.g., Food, Petrol): ")
        amount = int(input("Enter amount spent (in Rs): "))
        category = input("Enter category (e.g., Needs, Wants): ")
        add_expense(name, amount, category)
        
    elif choice == '2':
        df_res = display_expenses()
        if df_res is not None:
            print("\n--- ALL EXPENSES DATA ---")
            display(df_res)
            
    elif choice == '3':
        total = get_total_expenses()
        print(f"\n Total money spent so far: Rs. {total}")
        
    elif choice == '4':
        cat_to_filter = input("Enter category to filter (e.g., Needs): ")
        df_filtered = filter_expenses(cat_to_filter)
        if df_filtered is not None:
            print(f"\n Expenses for Category '{cat_to_filter}':")
            display(df_filtered)
            
    elif choice == '5':
        print("\n System is closing. Take care of your budget! Allah Hafiz!")
        break
        
    else:
        print("\n Invalid choice! Please select between 1 and 5.")

--- Personal Expense Tracker ---
1. Add Expense
2. View All Expenses
3. View Total Expenses
4. Filter Expenses by Category
5. Exit

User choice (1-5):  1
Enter expense name (e.g., Food, Petrol):  food
Enter amount spent (in Rs):  500
Enter category (e.g., Needs, Wants):  needs

 Expense 'food' added successfully!

--- Personal Expense Tracker ---
1. Add Expense
2. View All Expenses
3. View Total Expenses
4. Filter Expenses by Category
5. Exit

User choice (1-5):  1
Enter expense name (e.g., Food, Petrol):  petrol
Enter amount spent (in Rs):  800
Enter category (e.g., Needs, Wants):  wants

 Expense 'petrol' added successfully!

--- Personal Expense Tracker ---
1. Add Expense
2. View All Expenses
3. View Total Expenses
4. Filter Expenses by Category
5. Exit

User choice (1-5):  2

--- ALL EXPENSES DATA ---

  Expense Name  Amount Category
0         food     500    needs
1       petrol     800    wants

--- Personal Expense Tracker ---
1. Add Expense
2. View All Expenses
3. View Total Expenses
4. Filter Expenses by Category
5. Exit

User choice (1-5):  3

 Total money spent so far: Rs. 1300

--- Personal Expense Tracker ---
1. Add Expense
2. View All Expenses
3. View Total Expenses
4. Filter Expenses by Category
5. Exit

User choice (1-5):  4
Enter category to filter (e.g., Needs):  needs

 Expenses for Category 'needs':

  Expense Name  Amount Category
0         food     500    needs

--- Personal Expense Tracker ---
1. Add Expense
2. View All Expenses
3. View Total Expenses
4. Filter Expenses by Category
5. Exit

User choice (1-5):  5

 System is closing. Take care of your budget! Allah Hafiz!